name: edengths nomencl
on:
  push:
    branches:
      - nomencl
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: nomencl
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: edengths.tex
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -jobname=edengths_nomencl"
      - name: Commit PDF to gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --all
          ls
          git checkout --track origin/gh-pages
          git add ./edengths_nomencl.pdf
          git commit -m "Update PDF" 
      - name: Push changes to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
