name: Test main build
on:
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: edengths.tex
          args: "-pdfps -file-line-error -halt-on-error -interaction=nonstopmode"
